#!/usr/bin/env pwsh
#
# Provisions everything the three demos need, then writes a ready-to-use .env
#
# Prerequisites:  az login   (and an active subscription)
# Runtime:        ~4 minutes. Do this BEFORE the session, not during it.
#
# Auth: the demos use your Azure AD identity (DefaultAzureCredential). This
# script disables local (SAS) auth on the Service Bus and Event Hubs
# namespaces and assigns your signed-in user the data roles it needs. No keys
# end up in .env. Newly assigned roles can take a few minutes to propagate.
#
# Cost note: Service Bus Standard and Event Hubs Standard are inexpensive but
# not free. Run infra/cleanup.ps1 when you are finished.

$ErrorActionPreference = 'Stop'

# ---- names -----------------------------------------------------------------
$SUFFIX   = if ($env:SUFFIX) { $env:SUFFIX } else { Get-Random -Maximum 32768 }
$LOCATION = if ($env:LOCATION) { $env:LOCATION } else { 'canadacentral' }
$RG       = if ($env:RG) { $env:RG } else { 'rg-eda-demo' }

$STORAGE  = "edademo$SUFFIX"
$SB_NS    = "sb-eda-demo-$SUFFIX"
$EH_NS    = "ehns-eda-demo-$SUFFIX"

$ORDER_QUEUE   = 'orders'
$RECEIPT_QUEUE = 'receipts'
$EVENTHUB      = 'telemetry'

function Say([string]$msg) {
    Write-Host ""
    Write-Host "==> $msg" -ForegroundColor White
}

$ME = az ad signed-in-user show --query id -o tsv

# ---- resource group --------------------------------------------------------
Say "Resource group: $RG ($LOCATION)"
az group create --name $RG --location $LOCATION --output none

# ---- storage: receipt queue ------------------------------------------------
Say "Storage account: $STORAGE"
az storage account create `
    --name $STORAGE --resource-group $RG --location $LOCATION `
    --sku Standard_LRS --kind StorageV2 --output none

$STORAGE_CONN = az storage account show-connection-string `
    --name $STORAGE --resource-group $RG --query connectionString -o tsv

az storage queue create --name $RECEIPT_QUEUE `
    --connection-string $STORAGE_CONN --output none

# Data-plane role for the signed-in user (the demos talk to queues over Azure AD).
$STORAGE_ID = az storage account show `
    --name $STORAGE --resource-group $RG --query id -o tsv
az role assignment create `
    --assignee $ME --role "Storage Queue Data Contributor" `
    --scope $STORAGE_ID --output none

$STORAGE_ACCOUNT_URL = "https://$STORAGE.queue.core.windows.net/"

# ---- service bus -----------------------------------------------------------
Say "Service Bus namespace: $SB_NS (Standard, Azure AD only)"
az servicebus namespace create `
    --name $SB_NS --resource-group $RG --location $LOCATION `
    --sku Standard --output none

Say "  queue: $ORDER_QUEUE"
az servicebus queue create `
    --name $ORDER_QUEUE --namespace-name $SB_NS --resource-group $RG `
    --max-delivery-count 5 `
    --default-message-time-to-live PT1H `
    --lock-duration PT30S `
    --output none

$SB_ID = az servicebus namespace show `
    --name $SB_NS --resource-group $RG --query id -o tsv
az role assignment create `
    --assignee $ME --role "Azure Service Bus Data Owner" `
    --scope $SB_ID --output none

# Disable SAS so the demo runs on Azure AD only, matching production guidance.
az servicebus namespace update `
    --name $SB_NS --resource-group $RG --disable-local-auth true --output none

$SB_NAMESPACE = "$SB_NS.servicebus.windows.net"

# ---- event hubs ------------------------------------------------------------
# 4 partitions: enough to demonstrate ordering and the parallelism ceiling.
# Partition count is FIXED at creation on Standard — choose deliberately.
Say "Event Hubs namespace: $EH_NS (Standard, Azure AD only)"
az eventhubs namespace create `
    --name $EH_NS --resource-group $RG --location $LOCATION `
    --sku Standard --output none

Say "  hub: $EVENTHUB (4 partitions, 1 day retention)"
az eventhubs eventhub create `
    --name $EVENTHUB --namespace-name $EH_NS --resource-group $RG `
    --partition-count 4 --cleanup-policy Delete --retention-time-in-hours 24 `
    --output none

$EH_ID = az eventhubs namespace show `
    --name $EH_NS --resource-group $RG --query id -o tsv
az role assignment create `
    --assignee $ME --role "Azure Event Hubs Data Owner" `
    --scope $EH_ID --output none

az eventhubs namespace update `
    --name $EH_NS --resource-group $RG --disable-local-auth true --output none

$EH_NAMESPACE = "$EH_NS.servicebus.windows.net"

# ---- output ----------------------------------------------------------------
$ENV_FILE = Join-Path $PSScriptRoot '..' | Join-Path -ChildPath '.env'
$TIMESTAMP = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")

$envContent = @"
# Generated by infra/provision.ps1 on $TIMESTAMP
# Resource group: $RG
# Auth: DefaultAzureCredential (az login). No keys here.

STORAGE_ACCOUNT_URL=$STORAGE_ACCOUNT_URL
RECEIPT_QUEUE=$RECEIPT_QUEUE

SERVICEBUS_NAMESPACE=$SB_NAMESPACE
ORDER_QUEUE=$ORDER_QUEUE

EVENTHUB_NAMESPACE=$EH_NAMESPACE
EVENTHUB_NAME=$EVENTHUB
EVENTHUB_CONSUMER_GROUP=`$Default
"@

Set-Content -Path $ENV_FILE -Value $envContent -NoNewline

Say "Done. Wrote $ENV_FILE"
Write-Host ""
Write-Host "  Resource group : $RG"
Write-Host "  Suffix         : $SUFFIX"
Write-Host ""
Write-Host "  Data-plane role assignments can take a few minutes to propagate."
Write-Host ""
Write-Host "  Next:  pip install -r requirements.txt"
Write-Host "         python 01_storage_queue/producer.py"
Write-Host ""
Write-Host "  When finished:  `$env:RG='$RG'; ./infra/cleanup.ps1"
Write-Host ""
